---
version: '2'
services:
  broker01:
    image: confluentinc/cp-kafka:7.5.0
    hostname: broker01
    container_name: broker01
    ports:
      - 9091:9091
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker01:39091,2@broker02:39092,3@broker03:39093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker01:29091,PLAINTEXT_HOST://localhost:9091'
      KAFKA_LISTENERS: 'PLAINTEXT://broker01:29091,CONTROLLER://broker01:39091,PLAINTEXT_HOST://localhost:9091'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  broker02:
    image: confluentinc/cp-kafka:7.5.0
    hostname: broker02
    container_name: broker02
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker01:39091,2@broker02:39092,3@broker03:39093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker02:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://broker02:29092,CONTROLLER://broker02:39092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  broker03:
    image: confluentinc/cp-kafka:7.5.0
    hostname: broker03
    container_name: broker03
    ports:
      - 9093:9093
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker01:39091,2@broker02:39092,3@broker03:39093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker03:29093,PLAINTEXT_HOST://localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker03:29093,CONTROLLER://broker03:39093,PLAINTEXT_HOST://localhost:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  kafka-ui:
    container_name: kafka-ui-zq
    image: provectuslabs/kafka-ui:latest
    ports:
      - 80:8080
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker01:29091

  kafka-init:
    image: docker.io/bitnami/kafka:latest
    command: 
      - "/bin/bash"
      - "-c"
      -  | 
        /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server broker01:29091 --create --if-not-exists --topic echo-requests --config cleanup.policy=compact
        /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server broker01:29091 --create --if-not-exists --topic echo-responses --config cleanup.policy=compact
    depends_on:
      - broker01
      - broker02
      - broker03
    init: true

  zilla:
    image: ghcr.io/aklivity/zilla:latest
    container_name: zilla
    depends_on:
      - broker01
      - broker02
      - broker03
    ports:
      - 8080:8080
    volumes:
      - ./zilla.yaml:/etc/zilla/zilla.yaml
      - ./proto/:/proto/
    command: start -v

  grpc-echo:
    image: fgarciacode/grpc-echo:v0.1.2
    ports:
      - 5001:5001